# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - rentaliqra

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      # Build React App
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: rentaliqra-frontend
        run: npm install

      - name: Build frontend
        working-directory: rentaliqra-frontend
        run: |
          CI= REACT_APP_BASE_URL=https://rentaliqra.azurewebsites.net npm run build

      - name: Copy React build output to Laravel public/
        run: |
          rm -rf rentaliqra-backend/public/assets rentaliqra-backend/public/static rentaliqra-backend/public/index.html
          cp -r rentaliqra-frontend/build/* rentaliqra-backend/public/

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'rentaliqra-backend/composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        working-directory: rentaliqra-backend
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      # Zip the backend directory for deployment
      - name: Zip backend project
        run: |
          cd rentaliqra-backend
          zip -r ../rentaliqra.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: rentaliqra.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Extract zip
        run: |
          unzip rentaliqra.zip -d rentaliqra
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'rentaliqra'
          slot-name: 'Production'
          package: rentaliqra
          